### ISSUE TITLE
TypeError: fg.sync is not a function

### ISSUE THREAD

**Issue by chenrui333** [jbaubree/sitemap-ts#96]
seeing some site build failure using latest sitemap-ts 1.7.2

```
1:02:48 PM: build error:
1:02:48 PM: fg.sync is not a function
1:02:48 PM: TypeError: fg.sync is not a function
1:02:48 PM:     at getRoutes (file:///opt/build/repo/node_modules/.pnpm/sitemap-ts@1.7.2/node_modules/sitemap-ts/dist/index.mjs:83:11)
1:02:48 PM:     at generateSitemap (file:///opt/build/repo/node_modules/.pnpm/sitemap-ts@1.7.2/node_modules/sitemap-ts/dist/index.mjs:132:18)
1:02:48 PM:     at Object.buildEnd (file:///opt/build/repo/runatlantis.io/.vitepress/config.ts.timestamp-1716397363039-ee4c35203ed95.mjs:219:5)
1:02:48 PM:     at build (file:///opt/build/repo/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_@types+node@20.12.12_sass@1.77.2_search-insights@2.14.0/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46795:30)
```

![image](https://github.com/jbaubree/sitemap-ts/assets/1580956/522c9426-7e54-44c0-ad2f-bf1a7472459d)

relates to https://github.com/runatlantis/atlantis/pull/4588

**Comment by jbaubree** [comment]
Hi, thanks for your report, i will work on it asap 👍

**Comment by jbaubree** [comment]
@chenrui333 Does `v1.7.3` fixes this issue ?

**Comment by chenrui333** [comment]
yeah, [works for me](https://github.com/runatlantis/atlantis/pull/4655), thanks! (I also switched to npm due to some plugin issue recently)

**Comment by chenrui333** [comment]
thanks for the quick turnaround. <3
